common: &common
  adapter: postgresql

development:
  <<: *common
  database: detentionlogs_development
  host: localhost

test:
  <<: *common
  database: detentionlogs_test

production:
  <<: *common
  database: detentionlogs_production

